config/routes.rb
C9Blog::Application.routes.draw do
  resources :entries
  root :to => "entries#index"

end

app/models/entry.rb
class Entry
  include Mongoid::Document
  include Mongoid::Timestamps

  field :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.order_by( [:created_at, :desc] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/index.html.erb
<% for entry in @entries %>
  <div class="entry">
    <p><%= entry.content %><p>
    <div class="entry-footer"><%= entry.created_at.strftime( "%Y-%m-%d" ) %></div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sayings</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="wrap">
    <div id="nav"></div>
    <div id="sidebar">
      <%= image_tag "static_images/facer.jpg" %>
      <ul>
        <li><%= link_to "about", "/static_pages/about.html" %></li>
        <li><%= link_to "weblog", entries_path %></li>
        <li><%= link_to "projects", "/static_pages/projects.html" %></li>
        <li><%= link_to "resume", "/static_pages/resume.pdf" %></li>
        <li><%= link_to "GitHub", "http://github.com/composit" %></li>
        <li><%= link_to "LinkedIn", "http://www.linkedin.com/in/composition9" %></li>
        <li><%= link_to "log in", "https://timely.composition9.com" %></li>
      </ul>
    </div>
    <div id="main">
      <div id="header">
        <h1>weblog</h1>
        <%= image_tag "static_images/c9_logo.png" %>
      </div>
      <%= yield %>
    </div>
    <div id="footer">
      Composition9 Design, LLC<br />
    </div>
  </div>
</body>
</html>